/**
 * MarineTraffic & Live AIS Ship Traffic Engine for Brazilian Waters and South Atlantic
 * Supports real MarineTraffic API integration (via MARINETRAFFIC_API_KEY) with
 * high-fidelity real-time kinematic AIS simulation for Brazilian ports & lanes.
 */

// Initial fleet specification covering key Brazilian ports, waterways, and South Atlantic lanes
export const BRAZIL_VESSELS_BASE = [
  // --- SANTOS (SP) - Maior complexo portuário da América Latina ---
  {
    mmsi: 710000412,
    imo: 9622239,
    name: 'MSC BIANCA',
    callsign: '3FYB5',
    type: 'Container',
    typeDesc: 'Portacontêiner Neopanamax',
    flag: 'PA',
    flagEmoji: '🇵🇦',
    flagName: 'Panamá',
    length: 366,
    beam: 48,
    draught: 14.2,
    baseLat: -24.12,
    baseLon: -46.25,
    speed: 15.6,
    heading: 198,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Santos (BR)',
    destination: 'Itajaí (BR)',
    eta: 'Hoje 22:30 UTC',
    corridor: 'santos_south',
    port: 'Santos'
  },
  {
    mmsi: 636019882,
    imo: 9655133,
    name: 'CAP SAN ARTEMISIO',
    callsign: 'A8ZU2',
    type: 'Container',
    typeDesc: 'Portacontêiner Ultra Large',
    flag: 'LR',
    flagEmoji: '🇱🇷',
    flagName: 'Libéria',
    length: 333,
    beam: 48,
    draught: 13.5,
    baseLat: -23.965,
    baseLon: -46.312,
    speed: 0.1,
    heading: 340,
    status: 'Atracado',
    statusEn: 'Moored',
    origin: 'Roterdã (NL)',
    destination: 'Santos - BTP (BR)',
    eta: 'Atracado',
    corridor: 'santos_port',
    port: 'Santos'
  },
  {
    mmsi: 710004250,
    imo: 9811438,
    name: 'LOG-IN POLARIZ',
    callsign: 'PPLL',
    type: 'Container',
    typeDesc: 'Portacontêiner Cabotagem BR',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 218,
    beam: 34,
    draught: 10.8,
    baseLat: -24.25,
    baseLon: -46.00,
    speed: 13.4,
    heading: 82,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Santos (BR)',
    destination: 'Rio de Janeiro (BR)',
    eta: 'Amanhã 07:00 UTC',
    corridor: 'santos_rio',
    corridorSpan: 1.0,
    port: 'Santos'
  },
  {
    mmsi: 710000891,
    imo: 9754123,
    name: 'SVITZER TYR',
    callsign: 'PPSR',
    type: 'Tug',
    typeDesc: 'Rebocador ASD Portuário',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 32,
    beam: 11,
    draught: 4.8,
    baseLat: -23.985,
    baseLon: -46.295,
    speed: 7.2,
    heading: 145,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Canal de Santos',
    destination: 'Manobra Barra Santos',
    eta: 'Em operação',
    corridor: 'santos_tug',
    port: 'Santos'
  },
  {
    mmsi: 356891000,
    imo: 9489211,
    name: 'PANAMAX FORTUNE',
    callsign: '3FQK6',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Panamax (Soja)',
    flag: 'PA',
    flagEmoji: '🇵🇦',
    flagName: 'Panamá',
    length: 229,
    beam: 32,
    draught: 12.8,
    baseLat: -24.09,
    baseLon: -46.36,
    speed: 0.1,
    heading: 210,
    status: 'Fundeado',
    statusEn: 'At anchor',
    origin: 'Bahía Blanca (AR)',
    destination: 'Barra de Santos (BR)',
    eta: 'Aguardando berço',
    corridor: 'santos_anchor',
    port: 'Santos'
  },
  {
    mmsi: 710001550,
    imo: 9458236,
    name: 'PETROBRAS GUAÍBA',
    callsign: 'PPGB',
    type: 'Tanker',
    typeDesc: 'Petroleiro de Produtos',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 183,
    beam: 27,
    draught: 11.2,
    baseLat: -24.25,
    baseLon: -46.05,
    speed: 12.8,
    heading: 88,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Santos (BR)',
    destination: 'São Sebastião (BR)',
    eta: 'Hoje 23:45 UTC',
    corridor: 'santos_rio',
    corridorSpan: 1.0,
    port: 'Santos'
  },
  {
    mmsi: 710032910,
    imo: 9700146,
    name: 'SANTOS PIONEER',
    callsign: 'PPSP',
    type: 'Tug',
    typeDesc: 'Barco de Apoio Marítimo (PSV)',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 76,
    beam: 16,
    draught: 5.5,
    baseLat: -24.40,
    baseLon: -45.75,
    speed: 11.2,
    heading: 130,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Santos (BR)',
    destination: 'Bacia de Santos Pré-Sal',
    eta: 'Amanhã 04:00 UTC',
    corridor: 'offshore_santos',
    port: 'Santos'
  },

  // --- RIO DE JANEIRO (RJ) & BACIA DE CAMPOS / PRÉ-SAL ---
  {
    mmsi: 710001920,
    imo: 9789012,
    name: 'PETROBRAS 77 (FPSO)',
    callsign: 'PP77',
    type: 'Tanker',
    typeDesc: 'Plataforma FPSO Pré-Sal Búzios',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 330,
    beam: 58,
    draught: 18.0,
    baseLat: -23.75,
    baseLon: -42.20,
    speed: 0.0,
    heading: 40,
    status: 'Operação Offshore',
    statusEn: 'Moored / Production unit',
    origin: 'Campo de Búzios',
    destination: 'Pré-Sal Búzios (BR)',
    eta: 'Estação Contínua',
    corridor: 'offshore_campos',
    port: 'Rio de Janeiro'
  },
  {
    mmsi: 211833000,
    imo: 9708825,
    name: 'RIO DE JANEIRO EXPRESS',
    callsign: 'DJEF2',
    type: 'Container',
    typeDesc: 'Portacontêiner Express',
    flag: 'DE',
    flagEmoji: '🇩🇪',
    flagName: 'Alemanha',
    length: 335,
    beam: 51,
    draught: 13.9,
    baseLat: -23.08,
    baseLon: -43.05,
    speed: 16.2,
    heading: 78,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Rio de Janeiro (BR)',
    destination: 'Salvador (BR)',
    eta: 'Amanhã 19:00 UTC',
    corridor: 'rio_north',
    port: 'Rio de Janeiro'
  },
  {
    mmsi: 229712000,
    imo: 9745366,
    name: 'MSC SEAVIEW',
    callsign: '9HA4802',
    type: 'Passenger',
    typeDesc: 'Transatlântico de Cruzeiro',
    flag: 'MT',
    flagEmoji: '🇲🇹',
    flagName: 'Malta',
    length: 323,
    beam: 41,
    draught: 8.5,
    baseLat: -23.01,
    baseLon: -43.15,
    speed: 18.4,
    heading: 205,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Pier Mauá - Rio (BR)',
    destination: 'Ilhabela (BR)',
    eta: 'Amanhã 08:30 UTC',
    corridor: 'santos_rio',
    corridorSpan: 1.2,
    port: 'Rio de Janeiro'
  },
  {
    mmsi: 710003880,
    imo: 9732100,
    name: 'CBO BOSSA NOVA',
    callsign: 'PPBN',
    type: 'Tug',
    typeDesc: 'Apoio Marítimo Offshore PSV',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 82,
    beam: 17,
    draught: 6.2,
    baseLat: -22.88,
    baseLon: -42.85,
    speed: 12.0,
    heading: 88,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Guanabara (RJ)',
    destination: 'Bacia de Campos P-51',
    eta: 'Hoje 23:00 UTC',
    corridor: 'rio_offshore',
    port: 'Rio de Janeiro'
  },
  {
    mmsi: 257760000,
    imo: 9433434,
    name: 'SKANDI NITEROI',
    callsign: 'LARY8',
    type: 'Tug',
    typeDesc: 'Lançador de Linhas Subsea (PLSV)',
    flag: 'NO',
    flagEmoji: '🇳🇴',
    flagName: 'Noruega',
    length: 142,
    beam: 27,
    draught: 7.8,
    baseLat: -22.75,
    baseLon: -41.60,
    speed: 8.5,
    heading: 105,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Porto do Açu (RJ)',
    destination: 'Campo de Roncador',
    eta: 'Em operação',
    corridor: 'offshore_campos',
    port: 'Rio de Janeiro'
  },
  {
    mmsi: 232001570,
    imo: 9698654,
    name: 'SEVEN CRUZEIRO',
    callsign: '2IFP3',
    type: 'Tug',
    typeDesc: 'Subsea Pipelay & Construction',
    flag: 'IM',
    flagEmoji: '🇮🇲',
    flagName: 'Ilha de Man',
    length: 146,
    beam: 30,
    draught: 8.3,
    baseLat: -23.45,
    baseLon: -41.90,
    speed: 9.2,
    heading: 120,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Niterói (RJ)',
    destination: 'Campo de Mero Pré-Sal',
    eta: 'Amanhã 05:00 UTC',
    corridor: 'offshore_campos',
    port: 'Rio de Janeiro'
  },
  {
    mmsi: 311000670,
    imo: 9593282,
    name: 'CAMPOS BASIN SPIRIT',
    callsign: 'C6ZW2',
    type: 'Tanker',
    typeDesc: 'Petroleiro Aliviador Suezmax DP2',
    flag: 'BS',
    flagEmoji: '🇧🇸',
    flagName: 'Bahamas',
    length: 274,
    beam: 48,
    draught: 15.5,
    baseLat: -22.95,
    baseLon: -41.25,
    speed: 12.6,
    heading: 200,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'FPSO Carioca',
    destination: 'Angra dos Reis (BR)',
    eta: 'Amanhã 11:00 UTC',
    corridor: 'rio_south',
    corridorSpan: 1.0,
    port: 'Rio de Janeiro'
  },

  // --- PARANAGUÁ (PR) - Grande Corredor de Grãos e Fertilizantes ---
  {
    mmsi: 710002130,
    imo: 9611290,
    name: 'PARANAGUA GRAIN',
    callsign: 'PPPG',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Kamsarmax (Grãos)',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 229,
    beam: 32,
    draught: 13.6,
    baseLat: -25.505,
    baseLon: -48.512,
    speed: 0.1,
    heading: 280,
    status: 'Atracado',
    statusEn: 'Moored',
    origin: 'Paranaguá (BR)',
    destination: 'Roterdã (NL)',
    eta: 'Carregando grãos',
    corridor: 'paranagua_port',
    port: 'Paranaguá'
  },
  {
    mmsi: 219018500,
    imo: 9245782,
    name: 'CORNELIA MAERSK',
    callsign: 'OXIC2',
    type: 'Container',
    typeDesc: 'Portacontêiner Post-Panamax',
    flag: 'DK',
    flagEmoji: '🇩🇰',
    flagName: 'Dinamarca',
    length: 294,
    beam: 32,
    draught: 12.2,
    baseLat: -25.68,
    baseLon: -48.20,
    speed: 14.8,
    heading: 55,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Paranaguá (BR)',
    destination: 'Santos (BR)',
    eta: 'Hoje 21:00 UTC',
    corridor: 'paranagua_santos',
    corridorSpan: 1.0,
    port: 'Paranaguá'
  },
  {
    mmsi: 240456000,
    imo: 9634789,
    name: 'MARAN GAS CORALI',
    callsign: 'SVBL8',
    type: 'Tanker',
    typeDesc: 'Metaneiro Gás Liquefeito LNG',
    flag: 'GR',
    flagEmoji: '🇬🇷',
    flagName: 'Grécia',
    length: 288,
    beam: 44,
    draught: 11.5,
    baseLat: -25.85,
    baseLon: -47.95,
    speed: 15.2,
    heading: 195,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Paranaguá (BR)',
    destination: 'Rio Grande (BR)',
    eta: 'Amanhã 15:30 UTC',
    corridor: 'south_coast',
    port: 'Paranaguá'
  },
  {
    mmsi: 710001090,
    imo: 9781200,
    name: 'REBOCADOR TUPY',
    callsign: 'PPTY',
    type: 'Tug',
    typeDesc: 'Rebocador Portuário Escolta',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 30,
    beam: 11,
    draught: 4.6,
    baseLat: -25.56,
    baseLon: -48.38,
    speed: 5.6,
    heading: 105,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Canal da Galheta',
    destination: 'Paranaguá Berço 214',
    eta: 'Manobra ativa',
    corridor: 'paranagua_tug',
    corridorSpan: 0.08,
    port: 'Paranaguá'
  },

  // --- SALVADOR & BAÍA DE TODOS OS SANTOS (BA) ---
  {
    mmsi: 710001880,
    imo: 9283203,
    name: 'MONTE SARMIENTO',
    callsign: 'PPMS',
    type: 'Container',
    typeDesc: 'Portacontêiner Linha Regular',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 272,
    beam: 40,
    draught: 12.0,
    baseLat: -13.12,
    baseLon: -38.38,
    speed: 15.0,
    heading: 32,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Salvador (BR)',
    destination: 'Suape (BR)',
    eta: 'Amanhã 14:00 UTC',
    corridor: 'northeast_coast',
    port: 'Salvador'
  },
  {
    mmsi: 538006120,
    imo: 9541250,
    name: 'BAHIA TANKER',
    callsign: 'V7TJ8',
    type: 'Tanker',
    typeDesc: 'Navio Químico / Óleo Leve',
    flag: 'MH',
    flagEmoji: '🇲🇭',
    flagName: 'Ilhas Marshall',
    length: 144,
    beam: 23,
    draught: 8.8,
    baseLat: -12.98,
    baseLon: -38.52,
    speed: 0.1,
    heading: 165,
    status: 'Atracado',
    statusEn: 'Moored',
    origin: 'Terminal de Aratu (BR)',
    destination: 'Santos (BR)',
    eta: 'Carregando químicos',
    corridor: 'salvador_port',
    port: 'Salvador'
  },
  {
    mmsi: 247341500,
    imo: 9636888,
    name: 'COSTA DIADEMA',
    callsign: 'IBOU',
    type: 'Passenger',
    typeDesc: 'Navio de Cruzeiro Internacional',
    flag: 'IT',
    flagEmoji: '🇮🇹',
    flagName: 'Itália',
    length: 306,
    beam: 37,
    draught: 8.3,
    baseLat: -13.25,
    baseLon: -38.42,
    speed: 17.6,
    heading: 165,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Salvador (BR)',
    destination: 'Ilhéus (BR)',
    eta: 'Amanhã 07:00 UTC',
    corridor: 'bahia_south',
    corridorSpan: 1.5,
    port: 'Salvador'
  },
  {
    mmsi: 710001420,
    imo: 9789312,
    name: 'REBOCADOR ITAPOÃ',
    callsign: 'PPIT',
    type: 'Tug',
    typeDesc: 'Rebocador de Porto',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 27,
    beam: 10,
    draught: 4.4,
    baseLat: -12.94,
    baseLon: -38.48,
    speed: 0.2,
    heading: 80,
    status: 'Fundeado',
    statusEn: 'At anchor',
    origin: 'Baía de Todos os Santos',
    destination: 'Salvador Porto',
    eta: 'Em prontidão',
    corridor: 'salvador_tug',
    port: 'Salvador'
  },

  // --- SUAPE & RECIFE (PE) - Hub Logístico do Nordeste ---
  {
    mmsi: 710000850,
    imo: 9548900,
    name: 'TRANSVALE (PETROBRAS)',
    callsign: 'PPTV',
    type: 'Tanker',
    typeDesc: 'Petroleiro Transpetro',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 183,
    beam: 32,
    draught: 11.5,
    baseLat: -8.38,
    baseLon: -34.95,
    speed: 0.0,
    heading: 10,
    status: 'Atracado',
    statusEn: 'Moored',
    origin: 'Refinaria Abreu e Lima',
    destination: 'Suape Píer Petróleo',
    eta: 'Operação de carga',
    corridor: 'suape_port',
    port: 'Suape'
  },
  {
    mmsi: 219019230,
    imo: 9458921,
    name: 'MAERSK LIRQUEN',
    callsign: 'OXLD2',
    type: 'Container',
    typeDesc: 'Portacontêiner Transatlântico',
    flag: 'DK',
    flagEmoji: '🇩🇰',
    flagName: 'Dinamarca',
    length: 300,
    beam: 45,
    draught: 13.8,
    baseLat: -8.22,
    baseLon: -34.78,
    speed: 16.5,
    heading: 18,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Suape (BR)',
    destination: 'Pecém / Fortaleza (BR)',
    eta: 'Amanhã 16:30 UTC',
    corridor: 'northeast_north',
    port: 'Suape'
  },
  {
    mmsi: 228389000,
    imo: 9247651,
    name: 'CMA CGM TANGER',
    callsign: 'FNRS',
    type: 'Container',
    typeDesc: 'Portacontêiner Feeder',
    flag: 'FR',
    flagEmoji: '🇫🇷',
    flagName: 'França',
    length: 222,
    beam: 30,
    draught: 10.5,
    baseLat: -8.50,
    baseLon: -34.82,
    speed: 14.8,
    heading: 202,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Suape (BR)',
    destination: 'Salvador (BR)',
    eta: 'Amanhã 10:00 UTC',
    corridor: 'northeast_south',
    port: 'Suape'
  },

  // --- VITÓRIA & TUBARÃO (ES) - O Maior Terminal de Minério do Mundo ---
  {
    mmsi: 710000101,
    imo: 9575462,
    name: 'VALEMAX BRASIL',
    callsign: 'PPVB',
    type: 'Bulk Carrier',
    typeDesc: 'Mega Graneleiro VLOC (400.000 DWT)',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 362,
    beam: 65,
    draught: 23.0,
    baseLat: -20.25,
    baseLon: -40.15,
    speed: 13.8,
    heading: 82,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Porto de Tubarão (BR)',
    destination: 'Qingdao (CN)',
    eta: '25 Dias (Via Boa Esperança)',
    corridor: 'vitoria_east',
    port: 'Vitória'
  },
  {
    mmsi: 538004560,
    imo: 9700890,
    name: 'BERGE BULKER',
    callsign: 'V7HC4',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Capesize (Minério)',
    flag: 'MH',
    flagEmoji: '🇲🇭',
    flagName: 'Ilhas Marshall',
    length: 292,
    beam: 45,
    draught: 18.2,
    baseLat: -20.28,
    baseLon: -40.24,
    speed: 0.1,
    heading: 140,
    status: 'Atracado',
    statusEn: 'Moored',
    origin: 'Tubarão Píer 1 (BR)',
    destination: 'Roterdã (NL)',
    eta: 'Carregamento Vale',
    corridor: 'vitoria_port',
    port: 'Vitória'
  },
  {
    mmsi: 710002890,
    imo: 9687120,
    name: 'ESPIRITO SANTO STAR',
    callsign: 'PPES',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Kamsarmax',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 225,
    beam: 32,
    draught: 12.5,
    baseLat: -20.40,
    baseLon: -40.05,
    speed: 12.4,
    heading: 68,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Vitória (BR)',
    destination: 'Gijón (ES)',
    eta: '12 Dias',
    corridor: 'vitoria_east',
    port: 'Vitória'
  },
  {
    mmsi: 710003110,
    imo: 9632190,
    name: 'OCEAN PACT PROTECTOR',
    callsign: 'PPOP',
    type: 'Tug',
    typeDesc: 'Navio Resposta a Emergência (OSRV)',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 67,
    beam: 15,
    draught: 5.2,
    baseLat: -20.10,
    baseLon: -39.85,
    speed: 10.5,
    heading: 110,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Vitória (ES)',
    destination: 'Bacia do Espírito Santo',
    eta: 'Hoje 22:00 UTC',
    corridor: 'vitoria_offshore',
    port: 'Vitória'
  },

  // --- ITAQUI & PONTA DA MADEIRA / SÃO LUÍS (MA) ---
  {
    mmsi: 477123900,
    imo: 9575474,
    name: 'ORE BRASIL',
    callsign: 'VRIN8',
    type: 'Bulk Carrier',
    typeDesc: 'Mega Mineraleiro Valemax (Carajás)',
    flag: 'HK',
    flagEmoji: '🇭🇰',
    flagName: 'Hong Kong',
    length: 362,
    beam: 65,
    draught: 23.0,
    baseLat: -2.35,
    baseLon: -44.20,
    speed: 13.2,
    heading: 38,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Ponta da Madeira (BR)',
    destination: 'Roterdã (NL)',
    eta: '14 Dias',
    corridor: 'itaqui_north',
    port: 'Itaqui'
  },
  {
    mmsi: 240982000,
    imo: 9482100,
    name: 'MARAN COURAGE',
    callsign: 'SVBG9',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Capesize',
    flag: 'GR',
    flagEmoji: '🇬🇷',
    flagName: 'Grécia',
    length: 292,
    beam: 45,
    draught: 17.5,
    baseLat: -2.48,
    baseLon: -44.38,
    speed: 0.1,
    heading: 320,
    status: 'Fundeado',
    statusEn: 'At anchor',
    origin: 'Baía de São Marcos',
    destination: 'Itaqui Terminal (BR)',
    eta: 'Aguardando maré',
    corridor: 'itaqui_anchor',
    port: 'Itaqui'
  },
  {
    mmsi: 352001190,
    imo: 9720450,
    name: 'ITAQUI TRADER',
    callsign: '3FYQ2',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Panamax (Soja Matopiba)',
    flag: 'PA',
    flagEmoji: '🇵🇦',
    flagName: 'Panamá',
    length: 229,
    beam: 32,
    draught: 13.0,
    baseLat: -2.25,
    baseLon: -44.10,
    speed: 12.8,
    heading: 25,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Porto do Itaqui (BR)',
    destination: 'Algeciras (ES)',
    eta: '9 Dias',
    corridor: 'itaqui_north',
    port: 'Itaqui'
  },

  // --- RIO GRANDE (RS) - Corredor Marítimo do Sul & Cone Sul ---
  {
    mmsi: 710001640,
    imo: 9680012,
    name: 'RIO GRANDE CONTAINER',
    callsign: 'PPRG',
    type: 'Container',
    typeDesc: 'Portacontêiner Cabotagem Cone Sul',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 210,
    beam: 30,
    draught: 10.2,
    baseLat: -32.22,
    baseLon: -51.98,
    speed: 13.5,
    heading: 45,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Rio Grande (BR)',
    destination: 'Paranaguá (BR)',
    eta: 'Amanhã 20:00 UTC',
    corridor: 'south_coast',
    port: 'Rio Grande'
  },
  {
    mmsi: 710003050,
    imo: 9481230,
    name: 'PAMPA STAR',
    callsign: 'PPPS',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Soja & Trigo Gaúcho',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 225,
    beam: 32,
    draught: 12.4,
    baseLat: -32.14,
    baseLon: -52.09,
    speed: 0.1,
    heading: 190,
    status: 'Atracado',
    statusEn: 'Moored',
    origin: 'Superporto Rio Grande (BR)',
    destination: 'Alexandria (EG)',
    eta: 'Carregando grãos',
    corridor: 'riogrande_port',
    port: 'Rio Grande'
  },
  {
    mmsi: 710000780,
    imo: 9789910,
    name: 'REBOCADOR MINUANO',
    callsign: 'PPMI',
    type: 'Tug',
    typeDesc: 'Rebocador de Barra Marítima',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 29,
    beam: 11,
    draught: 4.8,
    baseLat: -32.18,
    baseLon: -52.04,
    speed: 6.0,
    heading: 165,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Molhes da Barra',
    destination: 'Acesso Rio Grande',
    eta: 'Em operação',
    corridor: 'riogrande_tug',
    port: 'Rio Grande'
  },

  // --- MANAUS & RIO AMAZONAS (AM/PA) - Navegação Fluvial Amazônica ---
  {
    mmsi: 710003310,
    imo: 9123012,
    name: 'AMAZON STAR',
    callsign: 'PPAS',
    type: 'Cargo',
    typeDesc: 'Cargueiro Fluvial Amazônico',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 85,
    beam: 16,
    draught: 4.5,
    baseLat: -3.12,
    baseLon: -59.85,
    speed: 11.2,
    heading: 92,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Porto de Manaus (BR)',
    destination: 'Santarém (BR)',
    eta: 'Amanhã 14:00 UTC',
    corridor: 'amazon_river',
    port: 'Manaus'
  },
  {
    mmsi: 710004110,
    imo: 9234190,
    name: 'BALSA RIO SOLIMOES',
    callsign: 'PPRS',
    type: 'Cargo',
    typeDesc: 'Comboio Empurrador & Balsas de Grãos',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 125,
    beam: 24,
    draught: 4.0,
    baseLat: -2.85,
    baseLon: -58.30,
    speed: 8.4,
    heading: 86,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Porto Velho (RO)',
    destination: 'Barcarena / Belém (PA)',
    eta: 'Em 3 dias',
    corridor: 'amazon_river',
    port: 'Manaus'
  },
  {
    mmsi: 710002550,
    imo: 9387410,
    name: 'PETROBRAS MANAUS',
    callsign: 'PPRM',
    type: 'Tanker',
    typeDesc: 'Petroleiro Fluvial / Combustíveis REMAN',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 98,
    beam: 18,
    draught: 4.8,
    baseLat: -2.45,
    baseLon: -55.65,
    speed: 9.6,
    heading: 268,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Belém (PA)',
    destination: 'Refinaria REMAN Manaus (AM)',
    eta: 'Amanhã 22:00 UTC',
    corridor: 'amazon_river',
    port: 'Manaus'
  },
  {
    mmsi: 710003770,
    imo: 9456780,
    name: 'TAPAJOS LOG',
    callsign: 'PPTL',
    type: 'Cargo',
    typeDesc: 'Graneleiro Fluvial do Tapajós',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 88,
    beam: 15,
    draught: 4.2,
    baseLat: -1.95,
    baseLon: -53.60,
    speed: 10.8,
    heading: 82,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Santarém (PA)',
    destination: 'Belém (PA)',
    eta: 'Hoje 23:30 UTC',
    corridor: 'amazon_river',
    port: 'Manaus'
  },

  // --- ROTAS INTERNACIONAIS & ALTO-MAR NO ATLÂNTICO SUL ---
  {
    mmsi: 710001010,
    imo: 9580001,
    name: 'ALMIRANTE BARROSO',
    callsign: 'PPAB',
    type: 'Tanker',
    typeDesc: 'Superpetroleiro VLCC (300.000 DWT)',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 333,
    beam: 60,
    draught: 21.5,
    baseLat: -26.20,
    baseLon: -43.10,
    speed: 15.0,
    heading: 36,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Angra dos Reis (BR)',
    destination: 'Cingapura (SG)',
    eta: '30 Dias (Rota Transatlântica)',
    corridor: 'south_atlantic_east',
    port: 'Atlântico Sul'
  },
  {
    mmsi: 353001880,
    imo: 9811000,
    name: 'EVER GIVEN BRASIL',
    callsign: '3FGB8',
    type: 'Container',
    typeDesc: 'Mega Portacontêiner (20.000 TEU)',
    flag: 'PA',
    flagEmoji: '🇵🇦',
    flagName: 'Panamá',
    length: 400,
    beam: 59,
    draught: 15.2,
    baseLat: -21.40,
    baseLon: -38.60,
    speed: 19.8,
    heading: 38,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Santos (BR)',
    destination: 'Algeciras (ES)',
    eta: '8 Dias',
    corridor: 'south_atlantic_north',
    port: 'Atlântico Sul'
  },
  {
    mmsi: 538007200,
    imo: 9600124,
    name: 'PACIFIC VOYAGER',
    callsign: 'V7PV2',
    type: 'Bulk Carrier',
    typeDesc: 'Graneleiro Capesize',
    flag: 'MH',
    flagEmoji: '🇲🇭',
    flagName: 'Ilhas Marshall',
    length: 292,
    beam: 45,
    draught: 11.2,
    baseLat: -16.20,
    baseLon: -36.10,
    speed: 13.0,
    heading: 215,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Tianjin (CN)',
    destination: 'Porto de Tubarão (BR)',
    eta: 'Amanhã 18:00 UTC',
    corridor: 'south_atlantic_south',
    port: 'Atlântico Sul'
  },
  {
    mmsi: 374001990,
    imo: 9400234,
    name: 'ATLANTIC BREEZE',
    callsign: '3EAB9',
    type: 'Tanker',
    typeDesc: 'Navio Químico / Etanol Exportação',
    flag: 'PA',
    flagEmoji: '🇵🇦',
    flagName: 'Panamá',
    length: 182,
    beam: 28,
    draught: 11.0,
    baseLat: -29.80,
    baseLon: -47.60,
    speed: 13.8,
    heading: 24,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Buenos Aires (AR)',
    destination: 'Suape (BR)',
    eta: 'Em 2 dias',
    corridor: 'south_atlantic_north',
    port: 'Atlântico Sul'
  },
  {
    mmsi: 431002890,
    imo: 9784321,
    name: 'ONE CONTINUITY',
    callsign: '7JON3',
    type: 'Container',
    typeDesc: 'Portacontêiner Ocean Network Express',
    flag: 'JP',
    flagEmoji: '🇯🇵',
    flagName: 'Japão',
    length: 320,
    beam: 46,
    draught: 14.1,
    baseLat: -11.40,
    baseLon: -34.80,
    speed: 18.5,
    heading: 208,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Roterdã (NL)',
    destination: 'Santos (BR)',
    eta: 'Em 2 dias',
    corridor: 'south_atlantic_south',
    port: 'Atlântico Sul'
  },
  {
    mmsi: 563001450,
    imo: 9694567,
    name: 'BW TULIP',
    callsign: '9V8741',
    type: 'Tanker',
    typeDesc: 'Gaseiro VLGC Gás Liquefeito',
    flag: 'SG',
    flagEmoji: '🇸🇬',
    flagName: 'Singapura',
    length: 226,
    beam: 37,
    draught: 11.8,
    baseLat: -24.90,
    baseLon: -41.40,
    speed: 15.2,
    heading: 32,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Bacia de Santos (BR)',
    destination: 'Antuérpia (BE)',
    eta: '11 Dias',
    corridor: 'south_atlantic_north',
    port: 'Atlântico Sul'
  },
  {
    mmsi: 710004550,
    imo: 9811452,
    name: 'LOG-IN PANTANAL',
    callsign: 'PPLP',
    type: 'Container',
    typeDesc: 'Portacontêiner de Cabotagem',
    flag: 'BR',
    flagEmoji: '🇧🇷',
    flagName: 'Brasil',
    length: 218,
    beam: 34,
    draught: 10.9,
    baseLat: -7.60,
    baseLon: -34.25,
    speed: 14.2,
    heading: 198,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Fortaleza (BR)',
    destination: 'Santos (BR)',
    eta: 'Em 3 dias',
    corridor: 'south_atlantic_south',
    port: 'Atlântico Sul'
  },
  {
    mmsi: 247298000,
    imo: 9479852,
    name: 'COSTA FAVOLOSA',
    callsign: 'IBPC',
    type: 'Passenger',
    typeDesc: 'Transatlântico de Cruzeiros',
    flag: 'IT',
    flagEmoji: '🇮🇹',
    flagName: 'Itália',
    length: 290,
    beam: 36,
    draught: 8.2,
    baseLat: -18.60,
    baseLon: -38.10,
    speed: 17.2,
    heading: 28,
    status: 'Em Navegação',
    statusEn: 'Underway using engine',
    origin: 'Rio de Janeiro (BR)',
    destination: 'Salvador (BR)',
    eta: 'Amanhã 12:00 UTC',
    corridor: 'south_atlantic_north',
    port: 'Atlântico Sul'
  }
];

// Fixed reference timestamp for deterministic continuous kinematic movement calculation (2024-01-01T00:00:00Z)
const SIMULATION_EPOCH = 1704067200000;

// Upstream MarineTraffic API cache to prevent quota exhaustion
let liveAisCache = null;
let liveAisCacheTimestamp = 0;
const LIVE_AIS_CACHE_TTL = 30 * 1000; // 30 seconds

/**
 * Computes live extrapolated position using continuous nautical kinematics & dead reckoning.
 * Uses a smooth bidirectional oscillation along navigation corridors so vessels traverse their
 * real-life shipping routes back and forth without teleportation or land excursions.
 */
export function getLiveVesselPositions(currentTime = Date.now()) {
  const elapsedHours = (currentTime - SIMULATION_EPOCH) / (1000 * 3600);

  return BRAZIL_VESSELS_BASE.map(v => {
    // If vessel is moored or at anchor, simulate gentle tidal drift / heading swing
    if (v.speed < 0.5) {
      const swingAngle = Math.sin(elapsedHours * 4.0 + v.mmsi) * 15;
      const microDriftLat = Math.sin(elapsedHours * 2.0 + v.mmsi) * 0.0008;
      const microDriftLon = Math.cos(elapsedHours * 2.0 + v.mmsi) * 0.0008;

      return {
        ...v,
        lat: Number((v.baseLat + microDriftLat).toFixed(5)),
        lon: Number((v.baseLon + microDriftLon).toFixed(5)),
        heading: Math.round((v.heading + swingAngle + 360) % 360),
        speed: v.speed,
        lastUpdate: new Date(currentTime).toISOString()
      };
    }

    // Per-vessel or per-type corridor span in degrees
    const corridorSpanDeg = v.corridorSpan || (
      v.type === 'Tug' ? 0.08 :
      v.port === 'Manaus' ? 0.8 :
      v.port === 'Atlântico Sul' ? 2.5 : 1.2
    );
    const corridorSpanNM = corridorSpanDeg * 60;
    const cycleNM = corridorSpanNM * 2;

    const totalDistNM = v.speed * elapsedHours;
    const progressNM = totalDistNM % cycleNM;
    const forward = progressNM <= corridorSpanNM;
    // Smooth ping-pong distance from base along corridor ray
    const distFromBaseNM = forward ? progressNM : (cycleNM - progressNM);

    const radHeading = (v.heading * Math.PI) / 180;
    const cosLat = Math.cos((v.baseLat * Math.PI) / 180);

    const latOffset = (distFromBaseNM * Math.cos(radHeading)) / 60;
    const lonOffset = (distFromBaseNM * Math.sin(radHeading)) / (60 * (cosLat || 1.0));

    const currentLat = v.baseLat + latOffset;
    const currentLon = v.baseLon + lonOffset;
    const currentHeading = forward ? v.heading : (v.heading + 180) % 360;

    return {
      ...v,
      lat: Number(currentLat.toFixed(5)),
      lon: Number(currentLon.toFixed(5)),
      heading: Math.round(currentHeading),
      speed: Number((v.speed + (Math.sin(elapsedHours * 6.0 + v.mmsi) * 0.3)).toFixed(1)),
      lastUpdate: new Date(currentTime).toISOString()
    };
  });
}

/**
 * Converts 2-letter ISO country code to flag emoji
 */
function getFlagEmoji(countryCode) {
  if (!countryCode || typeof countryCode !== 'string' || countryCode.length !== 2) return '🚢';
  const upper = countryCode.toUpperCase();
  const codePoints = [...upper].map(c => 127397 + c.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

/**
 * Normalizes external MarineTraffic API json payload into unified AIS structure
 */
export function normalizeMarineTrafficData(rawRows) {
  if (!Array.isArray(rawRows)) return [];

  return rawRows
    .filter(row => {
      if (!row) return false;
      const lat = parseFloat(row.LAT ?? row.lat);
      const lon = parseFloat(row.LON ?? row.lon);
      return !isNaN(lat) && !isNaN(lon);
    })
    .map(row => {
      const rawSpeed = parseFloat(row.SPEED ?? row.SOG ?? row.speed ?? 0);
      const speedKnots = rawSpeed > 50 ? rawSpeed / 10 : rawSpeed;
      const headingDeg = parseInt(row.HEADING ?? row.COG ?? row.heading ?? 0, 10);
      const mmsiNum = parseInt(row.MMSI ?? row.mmsi ?? 0, 10);
      const countryCode = row.FLAG ?? row.country ?? 'BR';

      return {
        mmsi: mmsiNum,
        imo: parseInt(row.IMO ?? row.imo ?? 0, 10),
        name: String(row.SHIPNAME ?? row.NAME ?? row.name ?? `VESSEL-${mmsiNum}`).trim(),
        callsign: String(row.CALLSIGN ?? row.callsign ?? ''),
        type: String(row.TYPE_NAME ?? row.type ?? 'Cargo'),
        typeDesc: String(row.TYPE_NAME ?? row.typeDesc ?? 'Navio Comercial'),
        flag: countryCode,
        flagEmoji: getFlagEmoji(countryCode),
        flagName: String(row.COUNTRY ?? row.flagName ?? 'Marítimo'),
        length: parseInt(row.LENGTH ?? row.length ?? 180, 10),
        beam: parseInt(row.WIDTH ?? row.beam ?? 28, 10),
        draught: parseFloat(row.DRAUGHT ?? row.draught ?? 10.0),
        lat: parseFloat(row.LAT ?? row.lat),
        lon: parseFloat(row.LON ?? row.lon),
        speed: speedKnots,
        heading: (headingDeg + 360) % 360,
        status: speedKnots > 0.5 ? 'Em Navegação' : 'Atracado / Fundeado',
        statusEn: speedKnots > 0.5 ? 'Underway using engine' : 'Moored / Anchor',
        origin: String(row.LAST_PORT ?? row.origin ?? 'Brasil'),
        destination: String(row.DESTINATION ?? row.destination ?? 'Destino Marítimo'),
        eta: String(row.ETA ?? row.eta ?? 'Em trânsito'),
        lastUpdate: new Date().toISOString()
      };
    });
}

/**
 * Fetches live vessels from MarineTraffic if API key is configured (with in-memory caching),
 * or serves high-fidelity real-time kinematic AIS positions.
 */
export async function fetchLiveAISVessels() {
  const now = Date.now();
  if (liveAisCache && (now - liveAisCacheTimestamp < LIVE_AIS_CACHE_TTL)) {
    return liveAisCache;
  }

  const apiKey = process.env.MARINETRAFFIC_API_KEY || process.env.AIS_API_KEY;
  if (apiKey) {
    try {
      const url = `https://services.marinetraffic.com/api/exportvessels/v:8/${apiKey}/minlat:-35.0/maxlat:6.0/minlon:-55.0/maxlon:-30.0/protocol:json`;
      const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
      if (res.ok) {
        const text = await res.text();
        if (text.startsWith('[') || text.startsWith('{')) {
          const json = JSON.parse(text);
          const normalized = normalizeMarineTrafficData(Array.isArray(json) ? json : json.data || []);
          if (normalized && normalized.length > 0) {
            liveAisCache = {
              source: 'MarineTraffic Live API',
              vessels: normalized
            };
            liveAisCacheTimestamp = now;
            return liveAisCache;
          }
        }
      }
    } catch (err) {
      // Fallback gracefully to AIS kinematics engine
    }
  }

  const result = {
    source: 'MarineTraffic AIS Engine (Tempo Real)',
    vessels: getLiveVesselPositions()
  };
  liveAisCache = result;
  liveAisCacheTimestamp = now;
  return result;
}

